feat : station command added
Improwised/devempire-nirav-thumar-backend pull request #11
Opened 2023-12-14 15:24 UTC by NiravThumar

- command name : go run main.go
use : this command is root command and use for displaying welcome message and formatted output

 How to run command
>go run app.go 

![rootcommand](https://github.com/Improwised/devempire-nirav-thumar-backend/assets/143510213/ff171d85-f98f-4c51-bb3e-49ecad41b4a9)

- command name : station
use : this is command display unique station name of source station and destination station with  count in tabular format

How to run command
> go run app.go station

![stationcommand](https://github.com/Improwised/devempire-nirav-thumar-backend/assets/143510213/e2149b71-a34f-4c3f-a2d5-074ba03607a4)

2023-12-15 07:38 UTC, NiravThumar commented
- When data is empty passed No Record Found message will  show

![NoRecordForStation](https://github.com/Improwised/devempire-nirav-thumar-backend/assets/143510213/0188a24a-d5ef-4dbf-80cc-8806474f5621)

2023-12-15 09:27 UTC, pratikbgit commented
@NiravThumar : I run the command : go run app.go and it will take more time but i run second time it will execute command fast.

cc: @Bhautik0110

2023-12-15 09:38 UTC, Bhautik0110 commented on data/data.go
> +}
make seperate file.

2023-12-15 09:40 UTC, Bhautik0110 commented on cli/main.go
> +		Short: "A brief description of your application",
replace with actual description.

2023-12-15 15:23 UTC, NiravThumar commented on cli/cmd/station.go
> +func GetStationCmd() cobra.Command {
Done

2023-12-15 15:24 UTC, NiravThumar commented on cli/cmd/station.go
> +		Use:   "station",
Done

2023-12-15 15:24 UTC, NiravThumar commented on cli/main.go
> +		Short: "A brief description of your application",
Done

2023-12-16 01:45 UTC, Bhautik0110 requested changes

2023-12-16 01:45 UTC, Bhautik0110 commented on cli/cmd/station.go
> +			destinationStationName := services.ReturnColumn(fileData, "DestinationStationName")               // gettind desttnation data
should be part of model, Not service.

2023-12-16 01:45 UTC, Bhautik0110 commented on models/trainInfo.go
> +}
here
`func ReadColumn`

2023-12-16 01:45 UTC, Bhautik0110 commented on models/trainInfo_test.go
> +	}
https://pkg.go.dev/github.com/stretchr/testify/assert#ElementsMatch

2023-12-16 01:45 UTC, Bhautik0110 commented on services/returnUniqueValueOfSlice.go
> +func ReturnUniqueValueOfSlice(slice []string) []string {
No need.

2023-12-16 01:45 UTC, Bhautik0110 commented on models/trainInfo.go
> +}
`func ListUniqueStationNames([]Train) []string)`

2023-12-16 01:45 UTC, Bhautik0110 commented on services/returnUniqueValueOfSlice.go
> +func ReturnUniqueValueOfSlice(slice []string) []string {
Service is not meant for utils.

2023-12-16 01:45 UTC, Bhautik0110 commented on cli/cmd/station.go
> +			uniqueStation := services.ReturnUniqueValueOfSlice(combineStations)                               // get uniquevalue from combine station
Make function `UniqueStationName` within `models/trainInfo.go`. Call this function.

2023-12-16 13:54 UTC, NiravThumar commented on cli/cmd/station.go
> +			destinationStationName := services.ReturnColumn(fileData, "DestinationStationName")               // gettind desttnation data
move to models

2023-12-16 13:57 UTC, NiravThumar commented on services/returnUniqueValueOfSlice.go
> +func ReturnUniqueValueOfSlice(slice []string) []string {
move to utils

2023-12-18 04:28 UTC, Bhautik0110 approved these changes

2023-12-18 04:28 UTC, merged